export const DYNAMIC_CLUSTER_DEFAULTS = {
  MAX_DOTS: 1500,
  SPAWN_INTERVAL_BASE: 0.01,
  LIFE_SPAN: 30,
  SIZE: 0.5,
  ORBIT_SIZE: 0.1,

  ORBIT_SPEED_BASE: 0.1,
  ORBIT_SPEED_MAX: 2.0,

  FADE_DURATION: 0.5,
  FADE_BUFFER: 0.2,
};
