import * as THREE from "three";
import FakeGlowMaterial from "./fakeGlowMaterial.js";

export const settings = {
  numSmall: 500,
  numLargeDots: 200,
  smallDotSize: 0.2,
  largeDotSize: 1.0,
  ringRadius: 2,
  sOrbitRadius: 0.1,
  lOrbitRadius: 0.02,
  sOrbitVariance: 1.0,
  lOrbitVariance: 0.5,
  sBaseOrbitSpeed: 1.5,
  lBaseOrbitSpeed: 0.2,
  targetZ: 10,
  targetRotation: 0,
  minZ: 2,
  maxZ: 10,
  minRotation: 0,
  maxRotation: 0.5,
  dotGeometry: new THREE.PlaneGeometry(0.1, 0.1),
  dotMaterial: new FakeGlowMaterial({}),
  reflectiveMaterial: null,
  minSpeedFactor: 0.3,
  maxSpeedFactor: 3.0,
  minOrbitMultiplier: 1.0,
  maxOrbitMultiplier: 2.0,
  animationProgress: 0,
  minScrollY: 0,
  maxScrollY: 1000,
};
